### ISSUE TITLE
How could an Ecommerce Transaction be created?

### ISSUE THREAD

**Issue by aragonet** [snowplow-incubator/snowplow-flutter-tracker#32]
I would like to know if there is a way to create an Ecommerce Transacion as described on the documentation here:

[https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/#tracking-ecommerce-transactions](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/#tracking-ecommerce-transactions)

**Comment by matus-tomlein** [comment]
Hi @aragonet, unfortunately, the tracker does not currently provide a way to track the same ecommerce events as the mobile trackers. However, this is also intentional because we plan to deprecate those events in favour of using self-describing events for ecommerce.

We already have schemas for the new ecommerce events and you can make use of them by tracking them using self-describing events with context entities. The schemas were introduced in the [e-commerce accelerator](https://docs.snowplow.io/accelerators/ecommerce/) (it only shows tracking using the JS tracker, but you can do the same in the Flutter tracker). There is only a single self-describing event schema – [the `snowplow_ecommerce_action`](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-0). The event is then described using context entites, you can [find all the schemas for them here](https://github.com/snowplow/iglu-central/tree/master/schemas/com.snowplowanalytics.snowplow.ecommerce).

We will provide APIs in the Flutter tracker to track these events and entities directly so keeping this issue open for that. However, as already mentioned, you can achieve the same result by following the schemas.
